### PR TITLE
fix: git reports some files stuck in modified state

### PR DESCRIPTION
**Pull request by OEvgeny**
I noticed `webui.sh` reported as modified even after `git reset --hard` happened which then prevents `git pull` from updating the repo.

Suggesting using the combination of:
```sh
git fetch
git reset --hard origin/master
```
to overcome the issue with files stuck in modified state in the cloned repo.

### CODE REVIEW

**Comment by TheLastBen** [comment]
I'll simply move `!rm webui.sh` below git reset hard, it'll be faster than `git reset --hard origin/master`, if the problem persists we'll do it your way

**Comment by OEvgeny** [comment]
Then it reports that the file is deleted. After the `git reset --hard` it appears as modified again.
I believe there is an issue with git in Google Drive: they don't play well

**Comment by TheLastBen** [comment]
I don't think git pull cares for missing files, but I'll check it out

**Comment by OEvgeny** [comment]
I don't want this to create unnecessary noise keeping this open. Just to point out that the PR resets all files which might or might not be a better option.

Closing this as the @TheLastBen's seems to work.

**Pull request closed without merging**
