### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by Klaushayan**
Added the missing dependencies
I don't know why these were missing, but some people including me couldn't run the colab and this fixes the issue.
#768 #787

edit: now that i think about it these should go in requirements, i should fix that

### CODE REVIEW

**Comment by TheLastBen** [comment]
The deps are uploading right now

**Comment by Klaushayan** [comment]
Oh those binary files were all of these dependencies bundled together?
Interesting. Alrighty then.

**Comment by dravid-cmyk** [comment]
> The deps are uploading right now

when it will be fixed @TheLastBen

**Comment by Klaushayan** [comment]
deps were added. closing this PR

**Pull request closed without merging**
