### PR TITLE
Refactor & simplify GPU check/download

### PR DESCRIPTION
**Pull request by Maw-Fox**
Sending a pull request upstream to introduce changes from our own downstream derivative colab.

### CODE REVIEW

**Comment by TheLastBen** [comment]
xformer() is needed in the next cell

**Comment by Maw-Fox** [comment]
Ah I see, it's a redundancy for things that break I suppose? I could wrap this stuff up in the xformers definition if you'd like.

**Comment by TheLastBen** [comment]
can you make the "unsupported GPU" error message loop every 5secs to the avoid moving to the next cell in case of a "run all"

**Comment by Maw-Fox** [comment]
Sure thing!

**Comment by TheLastBen** [comment]
so if the next cell is in standby, it won't run in case of GPU error ?

**Comment by Maw-Fox** [comment]
> so if the next cell is in standby, it won't run in case of GPU error ?

Yup. Understood.

**Comment by Maw-Fox** [comment]
Sorry about that, our colab is a fair bit different despite being based on your own, it's all one block for ease-of-use for people unfamiliar with colab.

**Pull request merged**
