### PR TITLE
Make notebooks universal

### PR DESCRIPTION
**Pull request by askiiart**
This makes all notebooks universal.

Instead of just using the colab folders, this uses `os.getcwd()` to get the folder it's started in and sets `working_dir` to that, then bases everything else off of `working_dir`.

### CODE REVIEW

**Comment by swcrazyfan** [comment]
This is a great idea, but what about the two dependencies files? Paperspace, uses Python 3.9 by default, but it seems Colab uses 3.7. Currently, the dependencies folder is set to extract to the python3.7 folder.

**Comment by askiiart** [comment]
@swcrazyfan Good catch, [it's fixed now](https://github.com/TheLastBen/fast-stable-diffusion/pull/150/commits/8978faaf2affa3524932cb28ee15a1462fabc993).

**Comment by swcrazyfan** [comment]
> @swcrazyfan Good catch, [it's fixed now](https://github.com/TheLastBen/fast-stable-diffusion/pull/150/commits/8978faaf2affa3524932cb28ee15a1462fabc993).

Cool! I'm actually specifically referring to the dependency installs. However, everything you fixed was also necessary! For example, the current notebook calls for two 7z files that extract into the python folder rather than installing them individually.

TheLastBen shared a notebook he's working on in an issue I shared about it. The only issue is that Paperspace's connection to GitHub is like 10x slower than Colab, so the dependencies install quite slow. He made a cell in the notebook with all dependencies.

You can see his first notebook here: https://github.com/TheLastBen/fast-stable-diffusion/issues/156

**Comment by askiiart** [comment]
@swcrazyfan Good catch again. I'll look into it when I've got time.

**Comment by askiiart** [comment]
So I'm kinda stuck on the dependencies 7z stuff. I could install the dependencies from their folder using pip, so that wouldn't be an issue. However, I'm not sure what I could do with the stuff inside `site-packages`, but not inside another subfolder, like `clip.egg-link`. Additionally, `clip.egg-link` references `/content/src/clip`, and I have no idea how many other things like that I'd have to adjust, or how I would adjust it.

Any ideas @swcrazyfan?

**Comment by TheLastBen** [comment]
@swcrazyfan thank you, these days I'm doing many changes on the notebooks, especially the Dreambooth one, making it universal right could cause some conflicts, but as soon as most of the new features are implemented and stable, I intend to make exclusive notebooks for each platform.

**Comment by askiiart** [comment]
Yeah, I've been quite busy lately, but I'm also down to help when I can.

**Comment by johndpope** [comment]
please fix

**Comment by askiiart** [comment]
I'm going to close this then, and just keep my repo as a separate fork.

**Comment by nawnie** [comment]
> I think I agree with making separate notebooks. The environments can be quite different on each platform, and one little change could mess it up.
> 
> I guess what I'd like to offer is making the notebooks first for Dreambooth but also for the others, once I have time. It seems like @askiiart is also down to help.

id love to help as well.

**Comment by johndpope** [comment]
It would make most sense to make readme say that this code only supports colab - and use askiiart's fork if you want local version.

**Comment by jtoy** [comment]
@askiiart so are you still building a universal notebook?

**Comment by askiiart** [comment]
> @askiiart so are you still building a universal notebook?

Yup. Just check out my fork [here](https://github.com/askiiart/universal-fast-stable-diffusion).

**Comment by johndpope** [comment]
also noteworthy -WebUI
https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/issues/79

 https://github.com/x-CK-x/Dreambooth-WebUI
https://github.com/smy20011/dreambooth-gui

**Comment by askiiart** [comment]
And:
[Cyberes/xformers-precompiled](https://github.com/Cyberes/xformers-compiled)
[Engineer-of-Stuff/stable-diffusion-paperspace](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace)

**Comment by askiiart** [comment]
And apparently @swcrazyfan made a functioning Dreambooth notebook for paperspace [here](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/issues/12)!

**Comment by askiiart** [comment]
@TheLastBen There's a also a lot of issues popping up asking about a local version, a paperspace version, etc. Maybe add a section in the readme or info in the Todo section about it?

**Comment by TheLastBen** [comment]
I will, the main holdback is that other services don't offer forms (check boxes and others) like colab does, and my colabs would be almost unusable without that, that's why the local version is only in colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/Local_fast_DreamBooth-Win.ipynb

**Comment by nawnie** [comment]
> You can't use Collab ?

not reliably, i tend to get cut off a lot and random restarts.

if its too much trouble i understand, or if it would take more email me at shawnohagan2@gmail.com and we can talk about that, I've tried to use the mentioned pulls but keep getting syntax errors (indents or magic cell becoming magic line due to mark down being on there.

with papers space i can pay 8 bucks and reliably start a machine begin training and walk away. and as ive stated id be more then happy to edit the asthetics and add notations to make it more user friendly i just need something that will run :D

**Comment by nawnie** [comment]
> I will, the main holdback is that other services don't offer forms (check boxes and others) like colab does, and my colabs would be almost unusable without that, that's why the local version is only in colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/Local_fast_DreamBooth-Win.ipynb

@TheLastBen 
Sir i will Send you a 20 on pateron or cash app to put it in on paper space, ill even then take your markdowns and notate them to make it more friendly on paperspace ive spent too much time trying to do this myself.. i wanna get back to making art.

**Comment by TheLastBen** [comment]
You can't use colab ?

**Comment by askiiart** [comment]
@nawnie Paperspace doesn't have anything special (like Colab has gdrive), it's basically just a hosted local runtime, right?

**Comment by nawnie** [comment]
> @nawnie Paperspace doesn't have anything special (like Colab has gdrive), it's basically just a hosted local runtime, right?

yes as far as I know. I did try pulling your files (askiiart) but still got a bunch of syntax errors

**Comment by nawnie** [comment]
it has a /storage/ to store things between notebooks, useful if running more then one machine
but thats all i think

**Comment by Cyberes** [comment]
If I may interject, the code for this universal notebook shouldn't be in one giant notebook but rather placed in external .py files and imported into the notebook. Otherwise the notebook will become monolithic.

**Comment by Cyberes** [comment]
I WILL PORT THIS DREAMBOOTH NOTEBOOK TO PAPERSPACE FOR $150

**Comment by TheLastBen** [comment]
@Cyberes this is not the place to sell your services

**Comment by Cyberes** [comment]
I take the "free" out of "free software"

**Comment by nawnie** [comment]
> I take the "free" out of "free software"

I have a feeling you already have one. sorry at 150 i may as well just buy the collab credits, wouldnt mind putting that much out over time for support however.

[askiiart] has already done the hard part, while i have your attention though ty for the textual inversion for paperspace :D

**Comment by johndpope** [comment]
don't know if this helps - https://github.com/kyrick/dreambooth-paperspace-hack

**Comment by nawnie** [comment]
Thanks I'll look into this

**Comment by nawnie** [comment]
This is a good start for sure, at the very least i can use this for animation styles. 

limited for sure, but i am getting better results for my (toriyama) style then embeddings where getting me.

**Pull request closed without merging**
