### PR TITLE
Fix missing comma in scheduler_config.json

### PR DESCRIPTION
**Pull request by gabrielpatronDK**
When training DreamBooth model using v1.5 I kept running into a **subprocess.CalledProcessError** in the training cell due to ill formatting in the scheduler_config.json file. Specifically, after trained_betas (null) parameter, there was a missing comma. This would give an invalid JSON file error when training the 1.5 model.

The output of scheduler_config.json file that looks like this: 

`{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.6.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "num_train_timesteps": 1000,
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
  "clip_sample": false
}`

Pretty strange, since the clip_sample parameter is modified in line 147 and trained_betas is modified in line 148, but this is what I get. Did not investigate further as I ran out of Colab credits.

Best,

### CODE REVIEW

**Comment by TheLastBen** [comment]
`"clip_sample": false` is removed with  `!sed -i 's@\"clip_sample\": false@@g'`, so that leaves  ` "trained_betas": null,` last, so the comma is removed with `!sed -i 's@\"trained_betas\": null,@\"trained_betas\": null@g'`

**Comment by gabrielpatronDK** [comment]
[PR_reproduce.zip](https://github.com/TheLastBen/fast-stable-diffusion/files/10313028/PR_reproduce.zip)

I have attached the zip file that contains the ipynb, and the resulting scheduler_config.json file, that reproduces the error that I get with the parameters I used, notably:

1. `"clip_sample": false` is not removed from scheduler_config.json
2.  The error then follows from a missing comma after `"trained_betas": null` because it is not last

The PR fix solves this issue, but there is certainly somewhere that is not working as intended. All this I obtained from a fresh notebook.

**Comment by TheLastBen** [comment]
is it the official 1.5 model from RunwayML ?

**Comment by gabrielpatronDK** [comment]
It should be, in Path_to_HuggingFace the value is set to runwayml/stable-diffusion-v1-5.

**Comment by TheLastBen** [comment]
try using the hf token to download the original and remove any link in the cell and see if it works

**Comment by gabrielpatronDK** [comment]
It works like this.

**Comment by TheLastBen** [comment]
would it also work with your modification ?

**Comment by gabrielpatronDK** [comment]
It does not work with the modification I made, there is a resulting trailing comma in the JSON file:

`{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.6.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "num_train_timesteps": 1000,
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null,
  
}
`

It throws an error in this scenario: `json.decoder.JSONDecodeError`. I can work on the solution if you got any ideas or preferred approach, but for now my modification breaks the code in this scenario.

**Pull request closed without merging**
